name: pitstop
services:
  postgres:
    image: postgres:18-alpine
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    environment:
      POSTGRES_DB_LIST: pitstop
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
      - 6435:5432
    volumes:
      - ./infra/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./infra/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ampsync:
    image: ghcr.io/edgeandnode/ampsync:latest
    command: ["sync"]
    environment:
      DATASET: "pitstop/pitstop@0.0.2"
      AMP_FLIGHT_ADDR: https://gateway.amp.staging.thegraph.com
      TABLES: "pitstop_transactions"
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pitstop?sslmode=disable
      AMP_AUTH_TOKEN: ${AMP_AUTH_TOKEN}
    restart: unless-stopped
    depends_on:
      - postgres

  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pitstop?sslmode=disable
      ELECTRIC_INSECURE: true
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - ampsync

volumes:
  postgres_data:
